#Spring
spring:
  #数据源配置
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: admin
    driver-class-name: net.sf.log4jdbc.DriverSpy

    #连接池配置    
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接: 连接池启动时创建的初始化连接数量
    initialSize: 8
    maxActive: 50
    #最大空闲连接: 连接池中容许保持空闲状态的最大连接数量,超过的空闲连接将被释放,如果设置为负数表示不限制
    maxIdle: 10
    #最大等待时间: 当没有可用连接时,连接池等待连接被归还的最大时间(以毫秒计数),超过时间则抛出异常,如果设置为-1表示无限等待
    maxWait: 30000
    #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
    testOnBorrow: true
    #SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前
    validationQuery: SELECT 1
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    #通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true
